### ISSUE TITLE
44Con 2016 video links broken (SSL cert domain name issues)

### ISSUE THREAD

**Issue by hartwork** [GoSecure/presentations#2]
Hi!

Just wanted to let you know that the three video links for 44Con 2016 are not working in practice, as of today.

Best, Sebastian

**Comment by obilodeau** [comment]
Thanks for letting us know. Two of the videos will be gone forever but I managed to scavenge some links to workshop repositories or more recent presentations of the same materials. See b0f96f1.

**Comment by hartwork** [comment]
Cool, thank you! :+1:
